### ISSUE TITLE
Remove Error from Poll

### ISSUE THREAD

**Issue by yoshuawuyts** [async-rs/futures-timer#14]
We're currently returning an `Result` from our `poll` method, which doesn't seem right. Most failure modes seem related to the `reset` method, which is useful but doesn't seem _crucial_. I think we should look into removing the error path so we don't need to `unwrap` from Runtime.

**Comment by yoshuawuyts** [comment]
ping @mmastrac do you perhaps have any ideas about this?

**Comment by mmastrac** [comment]
@yoshuawuyts Are you referring to `Delay` being `TryFuture` instead of `Future`? If that's the case, I believe the original design allowing for the associated `Timer` to go away. 

In theory a default-timer `Delay` should never fail.

If I'm reading this right, I'd be OK with switching Delay/Interval to panic or go away if the associated Timer drops.

**Comment by yoshuawuyts** [comment]
> If I'm reading this right, I'd be OK with switching Delay/Interval to panic or go away if the associated Timer drops.

Cool, yeah! -- I'm thinking `panic` might be the more conservative choice here; where if we were to resolve delays immediately in the absence of a timer, certain classes of problems might run into a lot of trouble.

**Comment by mmastrac** [comment]
Here's a strawperson whack at a possible API: we could have `Delay` and `TryDelay`. `Delay` panics, while `TryDelay` returns the existing error today.

We could also consider adding some parallel ext traits for futures - ie: `FutureExt::timeout` that wraps the return type in an `Option<>` instead of returning the timed-out error that currently exists.

If any that sounds reasonable, we could start designing the new API somewhere.

**Comment by yoshuawuyts** [comment]
Hmm, I think having two types is strictly worse than a single one that returns result.

I guess I'm more thinking along the lines of: is there a way to make this error proof.
